### ISSUE TITLE
Caddy with Labels for config

### ISSUE THREAD

**Issue by jgwehr** [jgwehr/homelab-docker#18]
https://github.com/lucaslorentz/caddy-docker-proxy

Example: https://p1ngouin.com/posts/why-i-migrated-from-traefik-to-caddy

**Comment by jgwehr** [comment]
Example from [Uptime Kuma docs](https://github.com/louislam/uptime-kuma/wiki/Reverse-Proxy#caddy-with-docker-compose)

```
version: '3'
networks:
  default:  
    name: 'proxy_network'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    volumes:  
      - /srv/uptime:/app/data
    labels:   
      caddy: status.example.org
      caddy.reverse_proxy: "* {{ '{{upstreams 3001}}'}}"
  caddy:
    image: "lucaslorentz/caddy-docker-proxy:ci-alpine"
    ports:    
      - "80:80" 
      - "443:443"
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/caddy/:/data
    restart: unless-stopped
    environment:
      - CADDY_INGRESS_NETWORKS=proxy_network
```
