### ISSUE TITLE
Try Gloomhaven Secretary

### ISSUE THREAD

**Issue by jgwehr** [jgwehr/homelab-docker#55]
https://github.com/Lurkars/gloomhavensecretary

Client
```yaml
  gloomhaven:
    build: https://github.com/Lurkars/gloomhavensecretary.git
    image: gloomhavensecretary
    ports:
      - 80:80
```

Server
```yaml
  gloomhaven-server:
    build: https://github.com/Lurkars/ghs-server.git
    image: gloomhavensecretary-server
    ports:
      - 8080:80
```

- [x] Client
- [x] Server
- [x] Caddy
